export const GET_DRIVERS_LOADING = 'GET_DRIVERS_LOADING'
export const GET_DRIVERS_SUCCESS = 'GET_DRIVERS_SUCCESS'
export const GET_DRIVERS_ERROR = 'GET_DRIVERS_ERROR'

export const ADD_DRIVER = 'ADD_DRIVERS'
export const DELETE_DRIVER = 'DELETE_DRIVERS'
export const DRIVERS_LOADING = 'DRIVERS_LOADING'

export const GET_ORDERS = 'GET_ORDERS'
export const LOADING_ORDERS = 'LOADING_ORDERS'

export const GET_CONFIRMED_ORDERS = 'GET_CONFIRMED_ORDERS'
export const ADD_CONFIRMED_ORDER = 'ADD_CONFIRMED_ORDER'
export const DELETE_CONFIRMED_ORDER = 'DELETE_CONFIRMED_ORDER'
export const LOADING_CONFIRMED_ORDER = 'LOADING_CONFIRMED_ORDER'

export const GET_POSTED_ORDERS = 'GET_POSTED_ORDERS'
export const ADD_POSTED_ORDER = 'ADD_POSTED_ORDER'
export const DELETE_POSTED_ORDER = 'DELETE_POSTED_ORDER'
export const LOADING_POSTED_ORDER = 'LOADING_POSTED_ORDER'