export default {
    GET_DRIVERS_LOADING: 'GET_DRIVERS_LOADING',
    GET_DRIVERS_SUCCESS: 'GET_DRIVERS_SUCCESS',
    GET_DRIVERS_ERROR: 'GET_DRIVERS_ERROR',

    GET_POSTED_ORDERS_LOADING: 'GET_POSTED_ORDERS_LOADING',
    GET_POSTED_ORDERS_SUCCESS: 'GET_POSTED_ORDERS_SUCCESS',
    GET_POSTED_ORDERS_ERROR: 'GET_POSTED_ORDERS_ERROR',

    GET_CONFIRMED_ORDERS_LOADING: 'GET_CONFIRMED_ORDERS_LOADING',
    GET_CONFIRMED_ORDERS_SUCCESS: 'GET_CONFIRMED_ORDERS_SUCCESS',
    GET_CONFIRMED_ORDERS_ERROR: 'GET_CONFIRMED_ORDERS_ERROR',

    GET_WS_LOADING: "GET_WS_LOADING",
    GET_WS_SUCCESS: "GET_WS_SUCCESS",
    GET_WS_ERROR: "GET_WS_ERROR",

    GET_ACTIVITY_LOADING: "GET_ACTIVITY_LOADING",
    GET_ACTIVITY_SUCCESS: "GET_ACTIVITY_SUCCESS",
    GET_ACTIVITY_ERROR: "GET_ACTIVITY_ERROR",
}